language: java

sudo: false

after_succes:
  - bash <(curl -s https://codecov.io/bash)

  notifications:
    email:
      recipient:
        -dmitriyshalimov@gmail.com
      on_success: always
      on_failure: always