language: java
jdk: oraclejdk8

install: true

sudo: false

after_succes:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -dmitriyshalimov@gmail.com
      -chickitosik@gmail.com
    on_success: always
    on_failure: always